parameters:
    kafka_brokers: '%env(KAFKA_BROKERS)%'
    kafka_topic: '%env(KAFKA_TOPIC)%'
    kafka_consumer_group: '%env(KAFKA_CONSUMER_GROUP)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\KafkaProducerService:
        arguments:
            $brokers: '%kafka_brokers%'
            $topic: '%kafka_topic%'

    App\Command\ConsumeKafkaCommand:
        arguments:
            $kafkaBrokers: '%kafka_brokers%'
            $kafkaTopic: '%kafka_topic%'
            $kafkaConsumerGroup: '%kafka_consumer_group%'
